### PR TITLE
Update index.html with 3 links on your card

### PR DESCRIPTION
**Pull request by Aayush-Bhatt**

### CODE REVIEW

**Review by shivaylamba — COMMENTED** [review]
Can you provide screenshots of your changes? @aayush

**Comment by learn-2earn** [comment]
Screenshot (403)

**Comment by Aayush-Bhatt** [comment]
Screenshot (403)

**Comment by shivaylamba** [comment]
@Aayush-Bhatt can you show how it looks like live on your local website

**Comment by Aayush-Bhatt** [comment]
Sir, the visual output is the same as above  but after the changes I committed the cards are now working as a link which can redirect visitors to dedicated links.

**Comment by shivaylamba** [comment]
@Aayush-Bhatt then provide links for @midopooler for these links and not just the link of quora.com or other sites for that matter. It should have the links for @midopooler social media handles.

**Comment by Aayush-Bhatt** [comment]
sir for that , Midopooler should provide me his social media accounts link

**Comment by Aayush-Bhatt** [comment]
can you please accept my PR and give me Hacktoberfest-accepted label?

**Comment by shivaylamba** [comment]
@midopooler please provide the links

**Comment by midopooler** [comment]
@Aayush-Bhatt Leave the link part, I'll take care of that part. Also, merging this PR to master

**Review by midopooler — APPROVED** [review]

**Pull request merged**
