### PR TITLE
Midopooler's website changes

### PR DESCRIPTION
**Pull request by raghavdhingra**
I've removed commenting and added a section

### CODE REVIEW

**Review by midopooler — APPROVED** [review]
LGTM

**Comment by shivaylamba** [comment]
@raghavdhingra this is a spammy PR. I will inform hacktoberfest team

**Comment by raghavdhingra** [comment]
@midopooler please add hacktoberfest-accepted to the label

**Comment by raghavdhingra** [comment]
and also hacktoberfest in it

**Comment by midopooler** [comment]
Since you did PR before 3 Oct, the label is not required

**Pull request merged**
